### ISSUE TITLE
Sorry, something went wrong. Reload?

### ISSUE THREAD

**Issue by kallied** [Aus3D/Prusai3#4]
Using Chrome, i am getting this message when downloading the Hardware & Software Instructions.
I have tried RCLicking and downloading but doesn't open in pdf viewer @chrissbarr

**Comment by chrissbarr** [comment]
Apologies for the late delay - I fixed this, but forgot to reply here. The problem seemed to be that the file was larger than GitHub liked, so a compressed version was added.

Alternatively, downloading the whole repository (via Download Zip) will also let you grab a local copy of the file, and doesn't seem to care about the file size.

-Chris
